Docs for Faster Bulk-data Import
tidbcloud/dbaas-docs pull request #35
Opened 2021-01-11 09:49 UTC by handlerww

### What is changed, added or deleted? (Required)

### What is the related PR or file link(s)?

Reference link(s):

2021-01-11 09:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tidbcloud/dbaas-docs?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tidbcloud/dbaas-docs?pullRequest=35) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tidbcloud/dbaas-docs?pullRequest=35) it.</sub>

2021-01-11 11:42 UTC, july2993 approved these changes

2021-01-11 11:48 UTC, july2993 commented on faster-bulk-data-import.md
> +> You can refer to the documents about [Table Filter](https://docs.pingcap.com/tidb/dev/table-filter#cli). For the current stage, it can only support one table filter rule.
use stable branch docs lint?

2021-01-11 11:52 UTC, july2993 commented on faster-bulk-data-import.md
> +1. Download Dumpling
do we have any image for dumpling, I wonder user may run it at k8s?

2021-01-11 12:18 UTC, handlerww commented on faster-bulk-data-import.md
> +> You can refer to the documents about [Table Filter](https://docs.pingcap.com/tidb/dev/table-filter#cli). For the current stage, it can only support one table filter rule.
ok

2021-01-11 12:26 UTC, handlerww commented on faster-bulk-data-import.md
> +1. Download Dumpling
There is no mention of k8s. Running on K8S is fine because Dumpling can directly write to S3.

But for another question, I have added the suggestion to prepare an EC2, and recommend to run EC2 on the same network with Aurora and S3 to avoid extra fees.

2021-01-11 13:09 UTC, lilin90 commented
I'll have a language review soon.

2021-01-12 08:10 UTC, lilin90 requested changes
I see that 17 images are used in this single doc. Generally, we would suggest limiting the use of an image if it is not really necessary and does not affect users' understanding.

Would you please take another look and see whether they're all necessary? It's ok if you think they're all necessary. Then I'll take a second look. Thanks!

2021-01-12 08:10 UTC, lilin90 commented on faster-bulk-data-import.md
> +---
About the file name, could you make it more specific so users can know from the url directly what this doc is about? For example, `migrate-from-amazon-aurora-to-tidb-cloud.md` if it's appropriate.

2021-01-13 13:01 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +Currently, there are two options to prepare data. Option 1 is to prepare source data files with [Dumpling](https://docs.pingcap.com/tidb/stable/dumpling-overview). You need to launch Dumpling on your
```suggestion
To prepare data, you can select one from the following two options:

- [Option 1: Prepare source data files using Dumpling](#option-1-prepare-source-data-files-using-dumpling)

    You need to launch [Dumpling](https://docs.pingcap.com/tidb/stable/dumpling-overview) on your EC2, and export the data to Amazon S3. The data you export is the current latest data of your source database. This might affect the online service. Dumpling will lock the table when you export data.

- [Option 2: Prepare source data files using Amazon Aurora snapshots](#option-2-prepare-source-data-files-using-amazon-aurora-snapshots)

    This does affect your online service. It might take a while when you export data, because the export task on Amazon Aurora first restores and scales the database before exporting data to Amazon S3. For more details, see [Exporting DB snapshot data to Amazon S3](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_ExportSnapshot.html).
```

2021-01-13 13:04 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +### Prechecks and Preparations
```suggestion
### Prechecks and preparations
```

2021-01-13 13:05 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +> **Notice**:
```suggestion
> **Note:**
```

2021-01-13 13:07 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +> For the current stage, it’s not recommended to import the data more than 2TB
```suggestion
> Currently, it is not recommended to import more than 2 TB of data.
```

2021-01-13 13:09 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +> Before you start the migration, you need to do some prechecks and some preparations to ensure the migration smooth.
```suggestion
> Before starting the migration, you need to do the following prechecks and preparations.
```

2021-01-13 13:09 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +#### Ensure the enough free space
```suggestion
#### Ensure enough free space
```

2021-01-13 13:11 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +Ensure that the free space of your TiDB cluster is larger than the size of your data. It’s recommended that you should reserve 600GB free space on each TiKV node. You can add more TiKV nodes to fulfi
```suggestion
Ensure that the free space of your TiDB cluster is larger than the size of your data. It is recommended that you should reserve 600 GB free space on each TiKV node. You can add more TiKV nodes to fulfill your demand.
```

2021-01-13 13:16 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +```sql
```suggestion
{{< copyable "sql" >}}

```sql
```

2021-01-13 13:19 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +Currently, TiDB only supports the `utf8_general_ci` and `utf8mb4_general_ci` collation. For your convenience, we need to verify the collation settings of the database. You could execute these command
```suggestion
Currently, TiDB only supports the `utf8_general_ci` and `utf8mb4_general_ci` collation. To verify the collation settings of your database, execute the following command in the MySQL terminal connected to Aurora:
```

2021-01-13 13:21 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +The results show the following:
Are there other possible results? What does the following result mean to users? What if they encounter other results? 🤔
```suggestion
The result is as follows:
```

2021-01-13 13:23 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +If TiDB does not support your character set or collection, you could consider converting them to supported types. You could refer to [Character Set and Collation](https://docs.pingcap.com/tidb/stable
```suggestion
If TiDB does not support your character set or collation, consider converting them to supported types. For more details, see [Character Set and Collation](https://docs.pingcap.com/tidb/stable/character-set-and-collation).
```

2021-01-13 13:23 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +### Option 1: Prepare source data files with Dumpling
```suggestion
### Option 1: Prepare source data files using Dumpling
```

2021-01-13 13:28 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +### Option 2: Prepare source data files with Amazon Aurora snapshots
```suggestion
### Option 2: Prepare source data files using Amazon Aurora snapshots
```

2021-01-13 13:29 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +You need to prepare an EC2 to run the data export task below. It's better to run on the same network with Aurora and S3 to avoid extra fees.
```suggestion
You need to prepare an EC2 to run the following data export task. It's better to run on the same network with Aurora and S3 to avoid extra fees.
```

2021-01-13 13:29 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +1. Download Dumpling on EC2
```suggestion
1. Download Dumpling on EC2.
```

2021-01-13 13:30 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    Download the TiDB Toolkit
```suggestion
    Download the TiDB Toolkit:
```

2021-01-13 13:32 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    ```bash
```suggestion
    {{< copyable "shell-regular" >}}

    ```bash
```

2021-01-13 13:33 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +2. Grant write privilege for writing S3
```suggestion
2. Grant the write privilege for writing S3.
```

2021-01-13 13:34 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    You can grant write privilege with access key and security key of AWS account in the environment. You should create a specific keypair for preparing data and revoke the access key immediately aft
```suggestion
    You can grant the write privilege using the access key and security key of your AWS account in the environment. Create a specific key pair for preparing data, and revoke the access key immediately after you finish the preparation.
```

2021-01-13 13:35 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    ```bash
```suggestion
    {{< copyable "shell-regular" >}}

    ```bash
```

2021-01-13 13:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +3. Backup the source database to S3
```suggestion
3. Back up the source database to S3.
```

2021-01-13 13:37 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    ```bash
```suggestion
    {{< copyable "shell-regular" >}}

    ```bash
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    ```bash
```suggestion
    {{< copyable "sql" >}}

    ```bash
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +3. Import the structure of the database into the TiDB Cloud.
```suggestion
3. Import the schema of the database into TiDB Cloud. 
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    ```bash
```suggestion
    {{< copyable "sql" >}}

    ```bash
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> + 1. From the Amazon RDS dashboard, choose **Snapshots**, click the button **Take snapshots** to create a manual snapshot.
```suggestion
 1. From the Amazon RDS dashboard, choose **Snapshots**, and click **Take snapshots** to create a manual snapshot.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> + 2. Fill in the blank under **Snapshot Name**. Click **Take snapshot**. When you finished creating the snapshot, you will find the snapshot under the snapshot table.
- Please confirm the name "Take snapshot" because it's "Take snapshots" in the last step.
```suggestion
 2. Fill in the blank under **Snapshot Name**. Click **Take snapshot**. When you finish creating the snapshot, the snapshot shows under the snapshot table.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> + 3. Choose the snapshot we took before, click **Actions**, under the drop-down box, click **Export to Amazon S3.**
```suggestion
 3. Choose the snapshot you have taken, click **Actions**. In the drop-down box, click **Export to Amazon S3**.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> + 4. Fill the blank under **Export identifier.**
```suggestion
 4. Fill the blank under **Export identifier**.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> + 5. Choose the amount of data to be exported. In this guide, we choose **All** You can also use partial to use identifiers to decide which part of the database need to export.
```suggestion
 5. Choose the amount of data to be exported. In this guide, **All** is selected. You can also choose partial to use identifiers to decide which part of the database needs to be exported.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> + 6. Choose the S3 bucket to store the snapshot. You can create a new bucket to store the data for security concerns. It’s recommended to use the bucket in the same region as your TiDB cluster. Downlo
```suggestion
 6. Choose the S3 bucket to store the snapshot. You can create a new bucket to store the data for security concerns. It is recommended to use the bucket in the same region as your TiDB cluster. Downloading data across regions can cause additional network costs.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> + 10. Currently, you need to edit the encryption key type of server-side encryption to Amazon S3 Key.
It seems that step 8 is not an operational step.

```suggestion
 7. Choose the proper IAM role to grant write access to S3 bucket. Now you can see the progress in the task table.

 8. From the task table, record the destination bucket (for example, s3://snapshot-bucket/snapshot-samples-1), fill it in the blank named **Bucket Name**.

 9. Modify the encryption key type of server-side encryption to Amazon S3 Key.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +     Choose the backup directory, and click the button **Actions**, in the pop list, click edit server-side encryption.
No need to keep words like "the button".
```suggestion
     Choose the backup directory, and click **Actions**. In the pop-up list, click to edit server-side encryption.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +     It may take a while depending on your database type and size.
```suggestion
     Choose **Amazon S3 key (SSE-S3)**. It might take a while, depending on your database type and size.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +## Learn how to create a Policy and Role for Cross-Account access
```suggestion
## Create a policy and role for cross-account access
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +For security concerns, you need to create a policy and role for cross-account access. There are two options to apply the bucket policy for cross-account access. You can do this on the AWS S3 manageme
```suggestion
For security concerns, you need to create a policy and role for cross-account access. You can use either of the following two options to apply the bucket policy for cross-account access:

- [Apply the bucket policy for cross-account access using AWS console](#apply-the-bucket-policy-for-cross-account-access-using-aws-console)
- [Apply the bucket policy for cross-account access using awscli](#apply-the-bucket-policy-for-cross-account-access-using-awscli)
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +5. Paste the policy data from the TiDB Cloud task dashboard, and apply the changes.  In this permission policy, we requested **GetObject** and **ListBucket** permissions.
```suggestion
1. Sign in to the AWS console and go to **S3 Manage Console**.
2. Choose the bucket that stores the data to import.
3. On the top panel, select **Permissions**.
4. Click **Edit** to edit **Bucket policy**.
5. Paste the policy data from the TiDB Cloud task dashboard, and apply the changes. In this permission policy, **GetObject** and **ListBucket** permissions are required.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +Once finished, you have created a policy and role for cross-account. You can go on the configuration on the migration dashboard.
```suggestion
Once finished, you have created a policy and role for cross-account. You can continue with the configuration on the migration dashboard.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +1. Install awscli and configure awscli according to your account info. You could refer to AWS cli configure quickstart to know how to get the information the awscli need. [https://docs.aws.amazon.com
```suggestion
1. Install awscli and configure awscli according to your account information. You can refer to [AWS cli configure quickstart](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html) to see how to get the information needed by awscli.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    ```bash
```suggestion
    {{< copyable "shell-regular" >}}

    ```bash
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +2. Export the data from the dashboard to the local file **policy.json**.
```suggestion
2. Export the data from the dashboard to the local file `policy.json`.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +## Learn how to set up filter rules
```suggestion
## Set up filter rules
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +> A: You have to grant ListBucket permission first before you have ListObject permission. You can refer to this [answer](https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-denied-listob
```suggestion
> To have the ListObject permission, you must get the ListBucket permission first, which is required by Amazon S3. For more details, see this [answer](https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-denied-listobjects-sync/) on AWS.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +You can refer to the documents about [Table Filter](https://docs.pingcap.com/tidb/stable/table-filter#cli). For the current stage, it can only support one table filter rule.
```suggestion
Refer to the [Table Filter](https://docs.pingcap.com/tidb/stable/table-filter#cli) document. Currently, TiDB Cloud only supports one table filter rule.
```

2021-01-13 14:38 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +## Learn how to clean up incomplete data
```suggestion
## Clean up incomplete data
```

2021-01-13 14:51 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +3. Execute the commands from the task dashboard to apply the bucket policy.
```suggestion
3. Execute the command from the task dashboard to apply the bucket policy.
```

2021-01-13 14:53 UTC, lilin90 approved these changes
LGTM

2021-01-14 04:03 UTC, SunRunAway commented on migrate-from-aurora-bulk-import.md
> +5. Paste the policy data from the TiDB Cloud task dashboard, and apply the changes. In this permission policy, **GetObject** and **ListBucket** permissions are required.
> TiDB Cloud task dashboard

Where is it? Cloud you link to that page?

2021-01-14 04:03 UTC, SunRunAway commented on migrate-from-aurora-bulk-import.md
> +### Apply the bucket policy for cross-account access using awscli
We should state to user that using AWS console or using awscli is one or the other.

2021-01-14 04:03 UTC, SunRunAway commented on migrate-from-aurora-bulk-import.md
> +    ![Apply bucket policy with awscli](media/migrate-from-aurora-bulk-import/guide-2.png)
Should it be a copyable command line, not an image?

2021-01-14 04:07 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +
@SunRunAway Please see https://github.com/tidbcloud/dbaas-docs/pull/35#pullrequestreview-566013654~

2021-01-14 05:01 UTC, handlerww commented on TOC.md
> +    + [Migrate from Aurora in Bulk](migrate-from-aurora-bulk-import.md)
fixed

2021-01-14 06:22 UTC, SunRunAway commented on migrate-from-aurora-bulk-import.md
> +This document describes how to migrate data from Amazon Aurora MySQL to TiDB Cloud in bulk.
All steps on the UI should be described.

2021-01-14 07:37 UTC, SunRunAway commented on migrate-from-aurora-bulk-import.md
> +Currently, you can only use the import tools on TiDB Cloud dashboard on the tier higher than `T1.tiny`. Generally, to import data, you need to do the following steps:
```suggestion
Currently, you can only use the import tools on TiDB Cloud console on the tier higher than `T1.tiny`. Generally, to import data, you need to do the following steps:
```

2021-01-14 07:37 UTC, SunRunAway commented on migrate-from-aurora-bulk-import.md
> +
Select `TiDB Dumpling` Data Format on the Data Import Task page.

2021-01-14 07:37 UTC, SunRunAway commented on migrate-from-aurora-bulk-import.md
> +
Select `Aurora Backup Snapshot` Data Format on the Data Import Task page.

2021-01-14 08:04 UTC, handlerww commented on migrate-from-aurora-bulk-import.md
> +
Next stage this description is needed, now CSV is not supported. The command params here is acceptable.

2021-01-14 08:50 UTC, SunRunAway reviewed
LGTM

2021-01-14 08:53 UTC, july2993 approved these changes

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +## Learn how to create a import task on TiDB Cloud dashboard
The word "dashboard" is a countable noun, so we need an article before. Please also check and update other similar places in this doc if necessary.
```suggestion
## Learn how to create an import task on the TiDB Cloud dashboard
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +Currently, you can only use the import tools on TiDB Cloud console on the tier higher than `T1.tiny`. Generally, to import data, you need to do the following steps:
Does "TiDB Cloud console" mean the same as "TiDB Cloud dashboard"? If yes, could you please make the words consistent to avoid possible confusion?

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +Currently, you can only use the import tools on TiDB Cloud console on the tier higher than `T1.tiny`. Generally, to import data, you need to do the following steps:
```suggestion
Currently, you can only use the import tools on TiDB Cloud console on the tier higher than `T1.tiny`. To import data, perform the following steps:
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +1. Click **Import** on the top of the cluster block on TiDB Cloud dashboard.
```suggestion
1. On the TiDB Cloud dashboard, click **Import** on the top of the cluster block. 
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +3. Fill the details about **Data Source Type**, **Bucket Name**, **Region**, and **Data Format** according to the specification of your source data.
```suggestion
3. Fill in the **Data Source Type**, **Bucket Name**, **Region**, and **Data Format** fields according to the specification of your source data.
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +4. Fill the details about **Username** and **Password** of the **Target Database** according to the connection settings of your cluster.
```suggestion
4. Fill in the **Username** and **Password** fields of the **Target Database** according to the connection settings of your cluster.
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +7. If your tasks failed, you can refer to [Learn how to clean up incomplete data](#learn-how-to-clean-up-incomplete-data).
This is not an ordinary step.
```suggestion

> **Note:**
>
> If your task fails, refer to [Learn how to clean up incomplete data](#learn-how-to-clean-up-incomplete-data).
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    This does affect your online service. It might take a while when you export data, because the export task on Amazon Aurora first restores and scales the database before exporting data to Amazon S
```suggestion
    This affects your online service. It might take a while when you export data, because the export task on Amazon Aurora first restores and scales the database before exporting data to Amazon S3. For more details, see [Exporting DB snapshot data to Amazon S3](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_ExportSnapshot.html).
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +2. Grant the write privilege for writing S3.
```suggestion
2. Grant the write privilege to Dumpling for writing S3.
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +    If you have assigned the IAM role to the EC2, you can skip configuring AK/SK, and run Dumpling on this EC2.
```suggestion
    > **Note:**
    >
    > If you have assigned the IAM role to the EC2, you can skip configuring the access key and security key, and directly run Dumpling on this EC2.
    
    You can grant the write privilege using the access key and security key of your AWS account in the environment. Create a specific key pair for preparing data, and revoke the access key immediately after you finish the preparation.

    {{< copyable "shell-regular" >}}

    ```bash
    export AWS_ACCESS_KEY_ID=AccessKeyID
    export AWS_SECRET_ACCESS_KEY=SecretKey
    ```
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +4. Choose **Data Format** to **TiDB Dumpling** on the data import task pannel of TiDB Cloud.
pannel -> panel
```suggestion
4. On the data import task panel of TiDB Cloud, choose **TiDB Dumpling** as the **Data Format**.
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +4. Choose **Data Format** to **Aurora Backup Snapshot** on the data import task pannel of TiDB Cloud.
```suggestion
4. On the data import task panel of TiDB Cloud, choose **Aurora Backup Snapshot** as the **Data Format**.
```

2021-01-14 09:36 UTC, lilin90 commented on migrate-from-aurora-bulk-import.md
> +5. Paste the policy data from the TiDB Cloud **Import Task Panel**, and apply the changes. In this permission policy, **GetObject** and **ListBucket** permissions are required. If there are bucket po
Incorrect grammar.
```suggestion
5. Paste the policy data from the TiDB Cloud **Import Task Panel**, and apply the changes. In this permission policy, **GetObject** and **ListBucket** permissions are required. If bucket policies exist, append the policies in **Statement** to your bucket policies list.
```

2021-01-14 10:04 UTC, lilin90 approved these changes
LGTM

2021-01-14 10:38 UTC, LinuxGit approved these changes
LGTM

2021-01-14 11:30 UTC, SunRunAway approved these changes

2021-01-14 11:31 UTC, SunRunAway commented
/merge

2021-01-14 11:38 UTC, merged